In [1]:
import numpy as np


Basic Array creation

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [7]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [8]:
b = [1,2,3.5,4,6]
np.array(b)

array([1. , 2. , 3.5, 4. , 6. ])

# Vectors and matrics

In [9]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Fuctions

In [14]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# arr = np.zeros(6)
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.ones((6,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
arr = np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

Random Generation function

In [24]:
np.random.rand(10)

array([0.19776486, 0.43649937, 0.8339844 , 0.01040347, 0.75704708,
       0.83593809, 0.43453813, 0.79931938, 0.10923508, 0.42901886])

In [25]:
np.random.randn(10)

array([ 0.58127909, -0.09641765,  0.04725548,  0.81128338, -0.8478988 ,
        0.56870286, -0.09103127, -0.89870381, -2.06834016,  0.21966726])

In [28]:
np.random.randint(10,20,10)

array([18, 16, 13, 19, 12, 10, 10, 11, 13, 15], dtype=int32)

Array Attributes

In [29]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.shape

(3, 3)

In [31]:
arr.size

9

In [32]:
arr.dtype

dtype('int64')

Array Methods

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.min()

np.int64(1)

In [37]:
arr.max()

np.int64(9)

In [38]:
arr.sum()

np.int64(45)

In [39]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [40]:
np.sum(arr,1)

array([ 6, 15, 24])

In [41]:
arr.mean()

np.float64(5.0)

In [42]:
arr.std()

np.float64(2.581988897471611)

In [44]:
arr.argmax()

np.int64(8)

In [45]:
arr.argmin()

np.int64(0)

Reshaping and resizing

In [47]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [50]:
#resize
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])