In [2]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [6]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[9]

np.int64(20)

In [27]:
arr[1:4]

array([12, 13, 14])

In [30]:
arr = np.arange(11,21)

In [31]:
arr[3:7]

array([14, 15, 16, 17])

In [32]:
arr[:5]

array([11, 12, 13, 14, 15])

In [33]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [36]:
arr[3::2]

array([14, 16, 18, 20])

In [37]:
arr[4]

np.int64(15)

In [38]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [39]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
arr[0]

array([1, 2, 3, 4, 5])

In [41]:
arr[0,0]

np.int64(1)

In [42]:
arr[3,3]

np.int64(19)

In [45]:
arr[5,4]

np.int64(30)

In [47]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [49]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [50]:
slice = arr[3::2,1::2]
slice

array([[17, 19],
       [27, 29]])

In [51]:
arr[:,1]

array([ 2,  7, 12, 17, 22, 27])

BOOLEAN INDEXING

In [56]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
bool_index = arr%2 == 0
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [57]:
arr = arr[bool_index]
arr

array([10, 12, 14, 16, 18, 20])