In [2]:
import numpy as np

ARRAY OPERATIONS

Arithmetic operations

In [6]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [7]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [8]:
a3 = np.array([1,2,3])

In [10]:
# a1+a3

BROADCASTING

In [11]:
l=[10,20,30,40]
arr = np.array(l)

In [12]:
arr+10

array([20, 30, 40, 50])

In [15]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

DEEP AND SHALLOW COPY

In [19]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
slice = a[0:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a[4:6] *10

array([50, 60])

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
a
b =a

In [27]:
b[0] = 99

In [28]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
b = a.copy()
b[0] = 10
b

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

matrix Operations

In [31]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [32]:
A

array([[1, 2],
       [3, 4]])

In [33]:
B

array([[5, 6],
       [7, 8]])

In [34]:
A * B

array([[ 5, 12],
       [21, 32]])

In [35]:
A @ B

array([[19, 22],
       [43, 50]])

In [37]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [38]:
A

array([[1, 2],
       [3, 4]])

In [39]:
A.T

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

Stacking Array

In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [43]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [44]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [47]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [49]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [50]:
a = np.vsplit(c,4)

In [51]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
