In [1]:
import numpy as np

In [2]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    
])

In [3]:
r = np.sum(s,axis=1)
for i in r:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [4]:
c = np.sum(s,axis=0)
for i in r:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("for column it is valid")

for column it is valid


In [5]:
s[:3,:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [6]:
s[:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [7]:
s[:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [9]:
for i in range(0,9,3):
    for j in range(0,9,3):
        # print(s[i:i+3, j:j+3])abs
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Questions

In [10]:
import numpy as np

In [47]:
# Cloumns : [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78],  #Student 1
    [19,92,88],  #Student 2
    [17,76,95],  #Student 3
    [18,65,70],  #Student 4
    [20,90,85],  #Student 5
])

In [18]:
#Get the shape of the matrix.
# np.shape(data)
data.shape

(5, 3)

In [20]:
#Find the average age of students.
# a = data[:,0]
# a
# np.mean(a)
np.mean(data[:,0])


np.float64(18.4)

In [17]:
# Extract Math marks of all students.
math_marks = data[:,1]
math_marks

array([85, 92, 76, 65, 90])

In [21]:
#find the highest Science marks.
np.max(data[:,2])

np.int64(95)

In [24]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [30]:
#Increase Math marks of all students by 5.
data[:,1] +=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [34]:
#Find how many students are younger then 19.
# data[data[:,0]<19]
len(data[data[:,0]<19])

3

In [36]:
#Calculate the average marks in each subject (column-wise mean).
# data[:,1:]
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [43]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [49]:
# Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75] = 0


In [51]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

In [52]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])